//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        internal static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        internal static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong captchar code.
        /// </summary>
        internal static string alertErrorCaptcha {
            get {
                return ResourceManager.GetString("alertErrorCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Date.
        /// </summary>
        internal static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Time.
        /// </summary>
        internal static string ArrivalTime {
            get {
                return ResourceManager.GetString("ArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival With Flight.
        /// </summary>
        internal static string ArrivalWithFlight {
            get {
                return ResourceManager.GetString("ArrivalWithFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Price Guaranted.
        /// </summary>
        internal static string BestPriceGuaranted {
            get {
                return ResourceManager.GetString("BestPriceGuaranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Price Guaranted.
        /// </summary>
        internal static string BestPriceGuaranted1 {
            get {
                return ResourceManager.GetString("BestPriceGuaranted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Tour.
        /// </summary>
        internal static string BookingTour {
            get {
                return ResourceManager.GetString("BookingTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        internal static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Tour.
        /// </summary>
        internal static string BookTour {
            get {
                return ResourceManager.GetString("BookTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        internal static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Availability.
        /// </summary>
        internal static string CheckAvailability {
            get {
                return ResourceManager.GetString("CheckAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        internal static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        internal static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for more details.
        /// </summary>
        internal static string Clickhereformoredetails {
            get {
                return ResourceManager.GetString("Clickhereformoredetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientFeedback.
        /// </summary>
        internal static string ClientFeedback {
            get {
                return ResourceManager.GetString("ClientFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  VND / Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        internal static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Date.
        /// </summary>
        internal static string DepartureDate {
            get {
                return ResourceManager.GetString("DepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        internal static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string hotel {
            get {
                return ResourceManager.GetString("hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel information.
        /// </summary>
        internal static string Hotelinformation {
            get {
                return ResourceManager.GetString("Hotelinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I read and agree with the agreemens and conditions of the .
        /// </summary>
        internal static string Igree {
            get {
                return ResourceManager.GetString("Igree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Room.
        /// </summary>
        internal static string InfoRoom {
            get {
                return ResourceManager.GetString("InfoRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make A Reservation.
        /// </summary>
        internal static string MakeAReservation {
            get {
                return ResourceManager.GetString("MakeAReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max People.
        /// </summary>
        internal static string MaxPeople {
            get {
                return ResourceManager.GetString("MaxPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messeger.
        /// </summary>
        internal static string Messeger {
            get {
                return ResourceManager.GetString("Messeger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string Mr {
            get {
                return ResourceManager.GetString("Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs.
        /// </summary>
        internal static string Mrs {
            get {
                return ResourceManager.GetString("Mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms.
        /// </summary>
        internal static string Ms {
            get {
                return ResourceManager.GetString("Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Rooms.
        /// </summary>
        internal static string NameRooms {
            get {
                return ResourceManager.GetString("NameRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orther Request.
        /// </summary>
        internal static string OrtherRequest {
            get {
                return ResourceManager.GetString("OrtherRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Articles.
        /// </summary>
        internal static string OtherArticles {
            get {
                return ResourceManager.GetString("OtherArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Rooms.
        /// </summary>
        internal static string OtherRooms {
            get {
                return ResourceManager.GetString("OtherRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Services.
        /// </summary>
        internal static string OtherServices {
            get {
                return ResourceManager.GetString("OtherServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Tours.
        /// </summary>
        internal static string OtherTours {
            get {
                return ResourceManager.GetString("OtherTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Events.
        /// </summary>
        internal static string OurEvents {
            get {
                return ResourceManager.GetString("OurEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Service.
        /// </summary>
        internal static string OurService {
            get {
                return ResourceManager.GetString("OurService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power by.
        /// </summary>
        internal static string PowerBy {
            get {
                return ResourceManager.GetString("PowerBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Night.
        /// </summary>
        internal static string PriceNight {
            get {
                return ResourceManager.GetString("PriceNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Article.
        /// </summary>
        internal static string RelatedArticle {
            get {
                return ResourceManager.GetString("RelatedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields.
        /// </summary>
        internal static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVE.
        /// </summary>
        internal static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string room {
            get {
                return ResourceManager.GetString("room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Article.
        /// </summary>
        internal static string RoomArticle {
            get {
                return ResourceManager.GetString("RoomArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Availability.
        /// </summary>
        internal static string SearchAvailability {
            get {
                return ResourceManager.GetString("SearchAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all event.
        /// </summary>
        internal static string Seeallevent {
            get {
                return ResourceManager.GetString("Seeallevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all news.
        /// </summary>
        internal static string Seeallnews {
            get {
                return ResourceManager.GetString("Seeallnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Ser {
            get {
                return ResourceManager.GetString("Ser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come to us you will receive the best services and incentives.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two cable.
        /// </summary>
        internal static string Service1 {
            get {
                return ResourceManager.GetString("Service1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make room: two times per day.
        /// </summary>
        internal static string Service10 {
            get {
                return ResourceManager.GetString("Service10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP check-in as requested.
        /// </summary>
        internal static string Service11 {
            get {
                return ResourceManager.GetString("Service11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily two complimentary bottled drinking water.
        /// </summary>
        internal static string Service12 {
            get {
                return ResourceManager.GetString("Service12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily complimentary shoeshine service.
        /// </summary>
        internal static string Service13 {
            get {
                return ResourceManager.GetString("Service13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily complimentary coffee &amp; tea.
        /// </summary>
        internal static string Service14 {
            get {
                return ResourceManager.GetString("Service14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture magazine in English.
        /// </summary>
        internal static string Service15 {
            get {
                return ResourceManager.GetString("Service15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry/ Pressing services.
        /// </summary>
        internal static string Service16 {
            get {
                return ResourceManager.GetString("Service16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office services.
        /// </summary>
        internal static string Service17 {
            get {
                return ResourceManager.GetString("Service17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room services.
        /// </summary>
        internal static string Service18 {
            get {
                return ResourceManager.GetString("Service18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed.
        /// </summary>
        internal static string Service2 {
            get {
                return ResourceManager.GetString("Service2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini bar.
        /// </summary>
        internal static string Service3 {
            get {
                return ResourceManager.GetString("Service3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shower.
        /// </summary>
        internal static string Service4 {
            get {
                return ResourceManager.GetString("Service4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair dryer.
        /// </summary>
        internal static string Service5 {
            get {
                return ResourceManager.GetString("Service5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic locking system.
        /// </summary>
        internal static string Service6 {
            get {
                return ResourceManager.GetString("Service6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot water.
        /// </summary>
        internal static string Service7 {
            get {
                return ResourceManager.GetString("Service7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string Service8 {
            get {
                return ResourceManager.GetString("Service8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Wifi.
        /// </summary>
        internal static string Service9 {
            get {
                return ResourceManager.GetString("Service9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking.
        /// </summary>
        internal static string Smoking {
            get {
                return ResourceManager.GetString("Smoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start From :.
        /// </summary>
        internal static string StartFrom {
            get {
                return ResourceManager.GetString("StartFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ur.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams &amp; Conditions.
        /// </summary>
        internal static string TeamsConditions {
            get {
                return ResourceManager.GetString("TeamsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Related.
        /// </summary>
        internal static string Tourrelated {
            get {
                return ResourceManager.GetString("Tourrelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        internal static string Utilities {
            get {
                return ResourceManager.GetString("Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW RATES FOR ALL ROOMS HERE.
        /// </summary>
        internal static string VIEWRATES {
            get {
                return ResourceManager.GetString("VIEWRATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Information.
        /// </summary>
        internal static string YourInformation {
            get {
                return ResourceManager.GetString("YourInformation", resourceCulture);
            }
        }
    }
}
